// <auto-generated />

using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace HabiCode.Api.Database.Migrations.HabiCode
{
    /// <inheritdoc />
    public partial class Add_UserId_Refrence : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.Sql(
                """
                DELETE FROM habi_code.habit_tags;
                DELETE FROM habi_code.habits;
                DELETE FROM habi_code.tags;
                """);

            migrationBuilder.DropIndex(
                name: "ix_tags_name",
                schema: "habi_code",
                table: "tags");

            migrationBuilder.AddColumn<string>(
                name: "user_id",
                schema: "habi_code",
                table: "tags",
                type: "character varying(500)",
                maxLength: 500,
                nullable: false,
                defaultValue: "");

            migrationBuilder.AddColumn<string>(
                name: "user_id",
                schema: "habi_code",
                table: "habits",
                type: "character varying(500)",
                maxLength: 500,
                nullable: false,
                defaultValue: "");

            migrationBuilder.CreateIndex(
                name: "ix_tags_user_id_name",
                schema: "habi_code",
                table: "tags",
                columns: new[] { "user_id", "name" },
                unique: true);

            migrationBuilder.CreateIndex(
                name: "ix_habits_user_id",
                schema: "habi_code",
                table: "habits",
                column: "user_id");

            migrationBuilder.AddForeignKey(
                name: "fk_habits_users_user_id",
                schema: "habi_code",
                table: "habits",
                column: "user_id",
                principalSchema: "habi_code",
                principalTable: "users",
                principalColumn: "id",
                onDelete: ReferentialAction.Cascade);

            migrationBuilder.AddForeignKey(
                name: "fk_tags_users_user_id",
                schema: "habi_code",
                table: "tags",
                column: "user_id",
                principalSchema: "habi_code",
                principalTable: "users",
                principalColumn: "id",
                onDelete: ReferentialAction.Cascade);
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropForeignKey(
                name: "fk_habits_users_user_id",
                schema: "habi_code",
                table: "habits");

            migrationBuilder.DropForeignKey(
                name: "fk_tags_users_user_id",
                schema: "habi_code",
                table: "tags");

            migrationBuilder.DropIndex(
                name: "ix_tags_user_id_name",
                schema: "habi_code",
                table: "tags");

            migrationBuilder.DropIndex(
                name: "ix_habits_user_id",
                schema: "habi_code",
                table: "habits");

            migrationBuilder.DropColumn(
                name: "user_id",
                schema: "habi_code",
                table: "tags");

            migrationBuilder.DropColumn(
                name: "user_id",
                schema: "habi_code",
                table: "habits");

            migrationBuilder.CreateIndex(
                name: "ix_tags_name",
                schema: "habi_code",
                table: "tags",
                column: "name",
                unique: true);
        }
    }
}
